name: Deploy to GitHub Pages using custom repository
on:
  push:
    branches: ['main']
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Use Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 22.13.0
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: built
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: built
          path: nostr
      - name: Clone repository which hosts pages
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'paulmillr/apps'
          token: ${{ secrets.GH_PAGES_APPS_PAT }}
          path: apps-pages
      - name: Add files to repositorory, remove previous build
        run: rm -rf apps-pages/nostr; mv nostr apps-pages
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cd apps-pages
          git add -A
          [[ -n "$(git diff --name-only)" ]] || exit 0
          git commit -m "deployed nostr"
          git push
