name: Deploy to GitHub pages
on:
  push:
    branches: ['main']
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v22
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          node-version: 22
      - run: npm install
      - run: npm run build
      - run: tar -cfz nostr.tar.gz dist
      - uses: actions/attest-build-provenance@bd77c077858b8d561b7a36cbe48ef4cc642ca39d # v2.2.2
        with:
          subject-path: nostr.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          path: nostr.tar.gz
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
      - run: tar -xf nostr.tar.gz && mv dist nostr
      - uses: actions/checkout@v4
        with:
          repository: 'paulmillr/apps'
          token: ${{ secrets.GH_PAGES_APPS_PAT }}
          path: apps-pages
      - run: mv nostr apps-pages
      - run: |
          cd apps-pages
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "deployed"
          git push
