name: Deploy to GitHub pages
on:
  push:
    branches: ['main']
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v22
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          node-version: 22
      - run: npm install
      - run: npm run build
      # dist dir
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'paulmillr/apps'
          token: ${{ secrets.GH_PAGES_APPS_PAT }}
          path: apps-pages
      - run: |
          ls -la
          mv dist apps-pages/nostr
          cd apps-pages
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "deployed"
          git push
